// Generated by CoffeeScript 1.7.1
var LoadPlugins, defaultPlugins, _;

_ = require('underscore');

defaultPlugins = ['component', 'css', 'js'];

module.exports.load = LoadPlugins = function() {
  var config, file, module, plugin, reqPlugins, _i, _len, _ref, _results;
  config = require('../config');
  if (!(config.plugins instanceof Array)) {
    config.plugins = [];
  }
  reqPlugins = _.union(defaultPlugins, config.plugins);
  _results = [];
  for (_i = 0, _len = reqPlugins.length; _i < _len; _i++) {
    plugin = reqPlugins[_i];
    console.log("Loading " + plugin + " plugin.");
    if (plugin.indexOf(".") === -1) {
      require("../plugins/" + plugin);
    }
    if (plugin.indexOf(".") !== -1) {
      _ref = plugin.split('.'), module = _ref[0], file = _ref[1];
      _results.push(require("" + module + "/" + file));
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};
