// Generated by CoffeeScript 1.6.3
var FSManager, RenderVars, getJson, _;

_ = require('underscore');

FSManager = require('./fs_manager');

RenderVars = {
  get: function(page, component, build) {
    var buildVars, retval;
    retval = {};
    if (component) {
      _.extend(retval, getJson('/comps/' + component + '/data.json'));
    }
    if (page) {
      _.extend(retval, getJson('/pages/' + page + '/data.json'));
    }
    if (build) {
      if (component) {
        _.extend(retval, getJson('/comps/' + component + '/data-build.json'));
        _.extend(retval, getJson('/comps/' + component + '/data-build-' + build + '.json'));
      }
      if (page) {
        _.extend(retval, getJson('/pages/' + page + '/data-build.json'));
        _.extend(retval, getJson('/pages/' + page + '/data-build-' + build + '.json'));
      }
      buildVars = {
        type: build
      };
      buildVars[build] = true;
      _.extend(retval, {
        build: buildVars
      });
    }
    return retval;
  }
};

getJson = function(file) {
  if (FSManager.exists(file)) {
    return JSON.parse(FSManager.readFile(file));
  }
  return {};
};

module.exports = RenderVars;
