// Generated by CoffeeScript 1.7.1
var EventManager, Router, componentController, pageController;

pageController = require('../controller/page');

EventManager = require('./event_manager');

componentController = require('../controller/component');

Router = {
  route: function(app) {
    app.get('/', pageController.redirectToHome);
    app.get('/p/:name', pageController.showPage);
    app.get('/page/:name', pageController.showPage);
    app.get('/pages', pageController.list);
    app.get('/c/:name', componentController.showComponent);
    app.get('/component/:name', componentController.showComponent);
    app.get('/components', componentController.list);
    return EventManager.raiseEvent('global', 'route', {}, {
      app: app
    }, function() {});
  }
};

module.exports = Router;
