// Generated by CoffeeScript 1.7.1
var EventManager, config, env, nunjucks, path;

nunjucks = require('nunjucks');

config = require('../config');

path = require('path');

EventManager = require('./event_manager');

env = nunjucks.configure(path.normalize("" + config.dir + "/macros"), {
  autoescape: false
});

module.exports = env;
