// Generated by CoffeeScript 1.7.1
var Element, ElementsList, EventManager, FSManager, renderComponent, templateEngine, updateComponentReferences, _;

EventManager = require('../../lib/event_manager');

ElementsList = require('../../lib/elements_list');

Element = require('../../lib/element');

EventManager = require('../../lib/event_manager');

ElementsList = require('../../lib/elements_list');

FSManager = require('../../lib/fs_manager');

_ = require('underscore');

updateComponentReferences = function(args, cb) {
  var availableComponents, compName, _i, _len;
  availableComponents = ElementsList.get("comps");
  for (_i = 0, _len = availableComponents.length; _i < _len; _i++) {
    compName = availableComponents[_i];
    args.template = args.template.replace(new RegExp("\{\{\\s*" + compName + "\\s*\}\}", "g"), "{{ '" + compName + "' | component }}");
  }
  return cb(null, args);
};

renderComponent = function(name, cb) {
  var comp;
  comp = new Element(name, 'comp');
  ElementsList.addComp(comp);
  return comp.render(function(e, template) {
    if (e == null) {
      cb(null, template);
    }
    if (e != null) {
      return cb(null, e.message);
    }
  });
};

EventManager.on('page', 'get_template', updateComponentReferences);

EventManager.on('comp', 'get_template', updateComponentReferences);

console.log("Adding component filter");

templateEngine = require('../../lib/template_engine');

templateEngine.addFilter('component', renderComponent, true);
