// Generated by CoffeeScript 1.7.1
var ComponentController, config;

config = require('../config');

ComponentController = {
  showComponent: function(req, res, next) {},
  list: function(req, res, next) {}
};

module.exports = ComponentController;
