// Generated by CoffeeScript 1.7.1
var Element, ElementsList, PageController, async, config;

config = require('../config');

ElementsList = require('../lib/elements_list');

Element = require('../lib/element');

async = require('async');

PageController = {
  showPage: function(req, res, next) {
    var pageEl;
    pageEl = new Element(req.params.name, 'page');
    ElementsList.addPage(pageEl);
    return async.mapSeries(['title', 'render', 'css', 'js'], function(fn, asyncCb) {
      return pageEl[fn](asyncCb);
    }, function(e, renderArgs) {
      var renderObj;
      renderObj = {};
      renderObj.title = renderArgs[0], renderObj.main = renderArgs[1], renderObj.css = renderArgs[2], renderObj.js = renderArgs[3];
      res.render('page', renderObj);
      return ElementsList.reset();
    });
  },
  list: function(req, res, next) {
    return res.render('pagelist', {
      pages: ElementsList.get('pages')
    });
  }
};

module.exports = PageController;
